### PR TITLE
Update travis: install cmake and see version.

### PR DESCRIPTION
**Pull request by hzeller**
We need cmake > 3.13 for #126

Signed-off-by: Henner Zeller <h.zeller@acm.org>

### CODE REVIEW

**Comment by hzeller** [comment]
(Let's wait for travis to finish before deciding to merge; I want to see if we actually pick up the latest version of cmake)

**Comment by hzeller** [comment]
Yeah, `cmake` version is ancient, let me do something more here...

**Comment by mithro** [comment]
https://github.com/SymbiFlow/symbiflow-arch-defs/blob/bc2709a7567c2aa48eddff3e57dca14377b6e128/.travis.yml#L5-L10

**Comment by mithro** [comment]
https://travis-ci.com/github/alainmarcel/UHDM/builds/162580268
```
$ cmake --version
cmake version 3.12.4
```
Is that what you where after?

**Comment by mithro** [comment]
Hrm...
```
Get:2 https://apt.kitware.com/ubuntu xenial/main amd64 cmake-data all 3.17.2-0kitware1 [1,687 kB]
Get:3 https://apt.kitware.com/ubuntu xenial/main amd64 cmake amd64 3.17.2-0kitware1 [7,423 kB]
```

**Comment by mithro** [comment]
Oh - IIRC @acomodi had this problem recently...

**Comment by mithro** [comment]
https://github.com/SymbiFlow/symbiflow-arch-defs/pull/1379/files

**Comment by mithro** [comment]
https://github.com/SymbiFlow/symbiflow-arch-defs/pull/1379#discussion_r397014377
> Turns out that the default cmake that is being used is the one shipped with xenial from Travis is 3.12.4, regardless of the kitware installation.
> 
> ```
> which cmake
> /usr/local/cmake-3.12.4/bin/cmake
> ```

https://github.com/SymbiFlow/symbiflow-arch-defs/pull/1379#discussion_r397317655

> Unsure, I believe it gets there as a default when using xenial. Another way probably to solve this issue is to use the apt.kitware package, as previously done, and then update the PATH to use the kitware cmake in the install step.



https://github.com/SymbiFlow/symbiflow-arch-defs/pull/1379#discussion_r397324446
> @acomodi Let's use the apt.kitware package and figure out how to make sure the `/usr/local/cmake-3.12.4/bin/cmake` is removed / not used. Worse comes to worse we can do a `sudo rm -rf /usr/local/cmake-3.12.4`

**Comment by hzeller** [comment]
Adding the path helped: https://travis-ci.com/github/alainmarcel/UHDM/builds/162581502#L371

@alainmarcel Ready to merge

**Pull request merged**
