### PR TITLE
Support for CI Builds on GHA

### PR DESCRIPTION
**Pull request by hs-apotell**
Support for CI Builds on GHA

* Includes Linux, MSYS+GCC and Windows+MSVS
* Fixed a few compile errors to support all configurations
* Added a few additional files/folders to ignore
* Don't assume LF for all editors across platforms
* Updated Makefile to support parallel builds

### CODE REVIEW

**Comment by hs-apotell** [comment]
@alaindargelas You might want to turn on GHA support on this repository to verify. I don't have the necessary permissions on this repository to do it. I haven't removed travis support just yet so the change can be verified. I can follow up with another PR to remove travis support.

**Comment by alaindargelas** [comment]
Build failed. Can't merge yet

**Comment by alaindargelas** [comment]
@umarcor can you help to enable the builds here too?

**Comment by hs-apotell** [comment]
A few problems with MSYS + GCC configurations -
* Builds are relatively slower than for other configurations (45 mins compared to Linux @ 10 mins and Windows @ 7mins)
* Builds are hitting memory limit during link. A wild guess - this has to do with growing size of some of the files (Serializer_Save, Serializer_Restore, vpi_user, vpi_listener, vpi_visitor and others). Specific reported error -
```
/usr/lib/gcc/x86_64-pc-msys/9.3.0/../../../../x86_64-pc-msys/bin/ld: CMakeFiles/test_inst.dir/tests/test1.cpp.o:test1.cpp:(.text+0x1627): undefined reference to `__imp_vpi_handle_by_name'
make: *** [Makefile:48: test_install] Error 1
CMakeFiles/test_inst.dir/tests/test1.cpp.o:test1.cpp:(.text+0x1627): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `__imp_vpi_handle_by_name'
```
I am going to disable the MSYS job for now until we figure out a good solution to improve the build times and also work out the limits on file sizes.

**Comment by umarcor** [comment]
@alaindargelas, see #363.

> Builds are relatively slower than for other configurations (45 mins compared to Linux @ 10 mins and Windows @ 7mins)

@hs-apotell, windows machines in GitHub Actions are slower are more I/O constrained than Linux machines. E.g., building and testing GHDL:

- Ubuntu 20, 14 min: https://github.com/ghdl/ghdl/runs/1296134910?check_suite_focus=true
- Windows MINGW64, 47 min: https://github.com/ghdl/ghdl/runs/1296134963?check_suite_focus=true 

> Builds are hitting memory limit during link. 

Can you please help fixing the current issue in #363, so I can reproduce this?

**Pull request merged**
