### PR TITLE
Use EXCLUDE_FROM_ALL in the capnp subproject to only build

### PR DESCRIPTION
**Pull request by hzeller**
what we need.

This should fix
  https://github.com/alainmarcel/Surelog/issues/170
and might help
  https://github.com/SymbiFlow/conda-packages/issues/68

Signed-off-by: Henner Zeller <h.zeller@acm.org>

### CODE REVIEW

**Comment by hzeller** [comment]
Interesting, I can't reproduce the travis failure locally. Need to look closer.

**Comment by hzeller** [comment]
This used to not work, but has been fixed in more recent cmake's. I wonder if travis uses an older one than the one on my workstation (3.16.3). Checking alternatives.

**Comment by hzeller** [comment]
ah ok. So the 3.13 version which, if I read it correctly in [the docs](https://cmake.org/cmake/help/v3.13/command/install.html#targets) is not the one installed on travis, thus the issue.

I wonder, can we require travis to use a later version of cmake or is it intentional to have a somewhat older version ? (3.13 is from November 2018)

**Comment by hzeller** [comment]
Updated so that the merge conflict is gone.

This pull request is still relevant, as it makes sure to not push all of capnp includes and libs in the regular system install locations (which not only pollutes that namespace but also messes up an existing installation. We should never overwrite other system library stuff with our library we happen to depend on and choose to compile privately).

As an example, this is the UHDM installation installing to `PREFIX=/tmp/u1`, **before** this change:

```
$ find /tmp/u1/ | egrep "capn|kj"
/tmp/u1/include/kj
/tmp/u1/include/kj/exception.h
/tmp/u1/include/kj/timer.h
/tmp/u1/include/kj/filesystem.h
/tmp/u1/include/kj/one-of.h
/tmp/u1/include/kj/time.h
/tmp/u1/include/kj/async-inl.h
/tmp/u1/include/kj/thread.h
/tmp/u1/include/kj/hash.h
/tmp/u1/include/kj/tuple.h
/tmp/u1/include/kj/table.h
/tmp/u1/include/kj/async-unix.h
/tmp/u1/include/kj/arena.h
/tmp/u1/include/kj/parse
/tmp/u1/include/kj/parse/common.h
/tmp/u1/include/kj/parse/char.h
/tmp/u1/include/kj/encoding.h
/tmp/u1/include/kj/main.h
/tmp/u1/include/kj/map.h
/tmp/u1/include/kj/common.h
/tmp/u1/include/kj/async.h
/tmp/u1/include/kj/units.h
/tmp/u1/include/kj/vector.h
/tmp/u1/include/kj/async-io.h
/tmp/u1/include/kj/async-win32.h
/tmp/u1/include/kj/mutex.h
/tmp/u1/include/kj/string-tree.h
/tmp/u1/include/kj/function.h
/tmp/u1/include/kj/memory.h
/tmp/u1/include/kj/async-prelude.h
/tmp/u1/include/kj/windows-sanity.h
/tmp/u1/include/kj/std
/tmp/u1/include/kj/std/iostream.h
/tmp/u1/include/kj/threadlocal.h
/tmp/u1/include/kj/io.h
/tmp/u1/include/kj/test.h
/tmp/u1/include/kj/debug.h
/tmp/u1/include/kj/refcount.h
/tmp/u1/include/kj/array.h
/tmp/u1/include/kj/string.h
/tmp/u1/include/kj/compat
/tmp/u1/include/kj/compat/http.h
/tmp/u1/include/kj/compat/gtest.h
/tmp/u1/include/kj/compat/gzip.h
/tmp/u1/include/kj/compat/url.h
/tmp/u1/include/capnp
/tmp/u1/include/capnp/c++.capnp
/tmp/u1/include/capnp/schema.h
/tmp/u1/include/capnp/stream.capnp
/tmp/u1/include/capnp/schema-parser.h
/tmp/u1/include/capnp/dynamic.h
/tmp/u1/include/capnp/rpc-prelude.h
/tmp/u1/include/capnp/serialize-packed.h
/tmp/u1/include/capnp/schema.capnp.h
/tmp/u1/include/capnp/endian.h
/tmp/u1/include/capnp/c++.capnp.h
/tmp/u1/include/capnp/pointer-helpers.h
/tmp/u1/include/capnp/pretty-print.h
/tmp/u1/include/capnp/std-iterator.h
/tmp/u1/include/capnp/stream.capnp.h
/tmp/u1/include/capnp/rpc-twoparty.capnp
/tmp/u1/include/capnp/membrane.h
/tmp/u1/include/capnp/rpc.capnp
/tmp/u1/include/capnp/message.h
/tmp/u1/include/capnp/layout.h
/tmp/u1/include/capnp/schema.capnp
/tmp/u1/include/capnp/schema-lite.h
/tmp/u1/include/capnp/raw-schema.h
/tmp/u1/include/capnp/rpc-twoparty.capnp.h
/tmp/u1/include/capnp/capability.h
/tmp/u1/include/capnp/common.h
/tmp/u1/include/capnp/schema-loader.h
/tmp/u1/include/capnp/ez-rpc.h
/tmp/u1/include/capnp/persistent.capnp.h
/tmp/u1/include/capnp/orphan.h
/tmp/u1/include/capnp/serialize-async.h
/tmp/u1/include/capnp/serialize-text.h
/tmp/u1/include/capnp/blob.h
/tmp/u1/include/capnp/serialize.h
/tmp/u1/include/capnp/persistent.capnp
/tmp/u1/include/capnp/rpc-twoparty.h
/tmp/u1/include/capnp/generated-header-support.h
/tmp/u1/include/capnp/list.h
/tmp/u1/include/capnp/any.h
/tmp/u1/include/capnp/rpc.h
/tmp/u1/include/capnp/compat
/tmp/u1/include/capnp/compat/json.capnp.h
/tmp/u1/include/capnp/compat/json.h
/tmp/u1/include/capnp/compat/json.capnp
/tmp/u1/include/capnp/rpc.capnp.h
/tmp/u1/bin/capnpc-c++
/tmp/u1/bin/capnpc
/tmp/u1/bin/capnpc-capnp
/tmp/u1/bin/capnp
/tmp/u1/lib/libcapnpc.a
/tmp/u1/lib/libkj-async.a
/tmp/u1/lib/libkj-test.a
/tmp/u1/lib/libkj-http.a
/tmp/u1/lib/libcapnp.a
/tmp/u1/lib/libcapnp-rpc.a
/tmp/u1/lib/libkj-gzip.a
/tmp/u1/lib/libkj.a
/tmp/u1/lib/libcapnp-json.a
/tmp/u1/lib/pkgconfig/kj-async.pc
/tmp/u1/lib/pkgconfig/capnp-json.pc
/tmp/u1/lib/pkgconfig/kj-test.pc
/tmp/u1/lib/pkgconfig/kj-http.pc
/tmp/u1/lib/pkgconfig/kj.pc
/tmp/u1/lib/pkgconfig/capnp-rpc.pc
/tmp/u1/lib/pkgconfig/capnp.pc
```

... and this is **afterwards**, installed with `PREFIX=/tmp/u2`

```
]$ find /tmp/u2/ | egrep "capn|kj"
/tmp/u2/lib/uhdm/libcapnp.a
/tmp/u2/lib/uhdm/libkj.a
```

Not only is it only the relevant stuff (not the compiler or other capnp headers), but also in a uhdm-private directory `/tmp/u2/lib/uhdm/libcapnp.a` vs. before in the prime-system location `/tmp/u1/lib/libcapnp.a`

However, we'd need cmake >= 3.13 for this.

**Comment by hzeller** [comment]
What do you think, should we cmake >= 3.13 ? Or do you see another way to avoid spilling all the non-relevant things into the installation ?

**Comment by alainmarcel** [comment]
Let's upgrade.

**Comment by hzeller** [comment]
mmh, we still need to upgrade the cmake so that this can be merged...

**Comment by alaindargelas** [comment]
Please reopen when you have a working pull requestThis was hanging for too long with a red status.

Sent from Yahoo Mail on Android 
 
  On Mon, Apr 27, 2020 at 12:00, Henner Zeller<notifications@github.com> wrote:   


mmh, we still need to upgrade the cmake so that this can be merged...

**Comment by alaindargelas** [comment]
Create an issue and assign it to Rafal for the cmake version
Sent from Yahoo Mail on Android 
 
  On Mon, Apr 27, 2020 at 12:00, Henner Zeller<notifications@github.com> wrote:   


mmh, we still need to upgrade the cmake so that this can be merged...

**Comment by alaindargelas** [comment]
I'd rather there is an issue for the update if cmake and a pull request opened when the issue is solved

Sent from Yahoo Mail on Android 
 
  On Mon, Apr 27, 2020 at 12:00, Henner Zeller<notifications@github.com> wrote:   


Reopened #126.

**Comment by hzeller** [comment]
Alright, with the cmake out of the way (#194 ), this now compiles and is ready to be merged.

Programs using uhdm should follow the example in the Makefile `test_install` and not include the sytem libraries `-ljk -lcapnp` but rather from the location where the uhdm lib is to be found `$(PREFIX)/lib/uhdm/libcapnp.a $(PREFIX)/lib/uhdm/libkj.a`

**Comment by alaindargelas** [comment]
Can you update the README to reflect that: $(PREFIX)/lib/uhdm/libcapnp.a $(PREFIX)/lib/uhdm/libkj.a ?

**Comment by hzeller** [comment]
Done.

**Pull request merged**
